core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    # home
    path('', views.index, name='index13'),
    path("product/", views.product_list_view, name='product-list'),

    # catygory
    path("category/", views.category_list, name='category-list'),
    path("category/<cid>", views.category_product_list, name='category_product_list'),
    
    # vendor
    path("vendor/", views.vendor_list_view, name='vendor_list'),
    path("vendor/<vid>", views.vendor_detail_view, name='vendor_detail_view'),

]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('user/',include('userauths.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from email.policy import default
from pyexpat import model
from unicodedata import decimal
from django.db import models
from shortuuid.django_fields import ShortUUIDField   ###
from django.utils.html import mark_safe  ##
from userauths.models import User



STATUS_CHOICE = (
    ("process", "Processing"),
    ("shipped", "Shipped"),
    ("delivered", "Delivered"),
)


STATUS = (
    ("draft", "Draft"),
    ("disabled", "Disabled"),
    ("rejected", "Rejected"),
    ("in_review", "In_Review"),
    ("published", "Published"),
)



RATING =(
    (1, "★☆☆☆☆"),
    (2, "★★☆☆☆"),
    (3, "★★★☆☆"),
    (4, "★★★★☆"),
    (5, "★★★★★"),
)


def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class Category(models.Model):
    cid =ShortUUIDField(unique=True, length=10, max_length=20, prefix="cat", alphabet="abcdefgh12345")
    title =models.CharField(max_length=100, default="food")
    image = models.ImageField(upload_to="category", default="category.jpg")

    class Meta:
        verbose_name_plural ="Categories"

    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
    
    def __str__(self):
        return self.title  
    
class Tags (models.Model):
    pass
    
class Vendor(models.Model):
    vid =ShortUUIDField(unique=True, length=10, max_length=20, prefix="ven", alphabet="abcdefgh12345")

    title =models.CharField(max_length=100, default="Naterfy")
    image = models.ImageField(upload_to=user_directory_path, default="vendor.jpg")
    cover_image = models.ImageField(upload_to=user_directory_path, default="vendor.jpg")
    description = models.TextField(null=True, blank=True, default="I am an amazging Vendor ")

    address = models.CharField(max_length=100, default="123 Main street.Lokogoma")
    contact = models.CharField(max_length=100, default="+234 (8167) 791 934")
    chat_resp_time = models.CharField(max_length=100, default="100")
    shipping_on_time = models.CharField(max_length=100, default="100")
    authentic_rating = models.CharField(max_length=100, default="100")
    days_return = models.CharField(max_length=100, default="100")
    warranty_period = models.CharField(max_length=100, default="100")


    user = models.ForeignKey(User, on_delete=models.SET_NULL, null= True)
    date =models.DateTimeField(auto_now_add=True, null=True, blank=True)


    class Meta:
        verbose_name_plural ="Vendors"

    def vendor_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
    
    def __str__(self):
        return self.title
    



class Product(models.Model):
    pid =ShortUUIDField(unique=True, length=10, max_length=20, alphabet="abcdefgh12345xvz")

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null= True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null= True, related_name="category")
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null= True, related_name='products')
    
    title =models.CharField(max_length=100, default="Fresh Pear")
    image = models.ImageField(upload_to=user_directory_path, default="product.jpg")
    description = models.TextField(null=True, blank=True, default="This is the product")

    price = models.DecimalField(max_digits=10, decimal_places=2, default="1.99")
    old_price = models.DecimalField(max_digits=10, decimal_places=2, default="2.99")

    specification = models.TextField(null=True, blank=True,)
    # tags = models.ForeignKey(Tags, on_delete=models.SET_NULL, null=True)

    product_status = models.CharField(choices= STATUS, max_length=10, default="in_review")


    status = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    featured = models.BooleanField(default=True)
    digital = models.BooleanField(default=True)

    sku =ShortUUIDField(unique=True, length=10, max_length=20, prefix="sku", alphabet="abcdefgh12345xvz")

    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(null=True, blank=True)


    class Meta:
        verbose_name_plural ="Products"

    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
    
    def __str__(self):
        return self.title
    
    def get_precentage(self):
        new_price = (self.price / self.old_price ) * 100
        return new_price



   
    
class ProductImages(models.Model):
    images = models.ImageField(upload_to="product-images", default="product.jpg")
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural ="Products Images"



 #################################### cart, order, ordderitems and address #############################










class CartOder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, default="1.99")
    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    product_status = models.CharField(choices= STATUS_CHOICE, max_length=30, default="processing")

    class Meta:
        verbose_name_plural ="Cart Order"   


class CartOderItems(models.Model):
    order = models.ForeignKey(User, on_delete=models.CASCADE)
    invoice_no = models.CharField( max_length=200)
    product_status = models.CharField( max_length=200)
    item = models.CharField( max_length=200 )
    image = models.CharField( max_length=200 )
    qty = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2, default="1.99")
    total = models.DecimalField(max_digits=10, decimal_places=2, default="1.99")


    class Meta:
        verbose_name_plural ="Cart Order Items"   


    def order_img(self):
        return mark_safe('<img src="/media/%s" width="50" />' % (self.image))
   



 #################################### product, review, wishlists and address #############################
 #################################### product, review, wishlists and address #############################
 #################################### product, review, wishlists and address #############################
 #################################### product, review, wishlists and address #############################



class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    review = models.TextField()
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural ="Product Reviews"   

    def __str__(self):
        return self.product.title 

    def get_rating(self):
        return self.rating



class WishList(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural ="wishLists"   

    def __str__(self):
        return self.product.title 


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=100, null=True)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural ="Address"   
       

core/views.py
from django.shortcuts import render
from core.models import Product, Category, Vendor, CartOder, CartOderItems, ProductImages, ProductReview, WishList, Address

# Create your views here.

def index(request):
    # product = Product.objects.all().order_by(("-id"))
    product = Product.objects.filter(product_status="published", featured =True)

    context ={
        'products':product
    }
    return render (request,'core/index13.html',context)


def product_list_view(request):
    product = Product.objects.filter(product_status="published")


    context ={
        'products':product
    }
    return render (request,'core/product_list.html',context)


def category_list(request):
    category = Category.objects.all()

    context ={
        'categorys':category
    }
    return render (request,'core/category_list.html',context)



def category_product_list(request, cid):
    category = Category.objects.get(cid=cid)
    products =Product.objects.filter(product_status="published",category=category)
    context = {
        'category':category,
        'products':products,
    }
    return render(request, 'core/category-product-list.html', context)


def vendor_list_view(request):
    vendors =Vendor.objects.all()
    context = {
        "vendors":vendors
    }
    return render(request, 'core/vendor-list.html',context)


def vendor_detail_view(request, vid):
    vendor =Vendor.objects.get(vid=vid)
    context = {
        "vendor":vendor
    }
    return render(request, 'core/vendor_detail_view.html',context)

templates/core/product_list.html
{% comment %} {% extends "core/base.html" %} {% endcomment %}



{% block content %}
{% comment %} {% include "core/nav.html" %} {% endcomment %}


<h1>Products List </h1>

{% for p in products%}
<div class="col-md-3">
    <div class="card product-card">
       <p><a href="">-{{p.get_precentage |floatformat:0 }}%</a></p>
        <img src="{{ p.image.url }}" width='30' class="card-img-top"  alt="Product 1">
        <div class="card-body">
            <p><a href="">{{p.category.title}}</a></p>
            <h5 class="card-title">{{p.title}}</h5>
            <p class="card-text" style="background-color: red;">{{p.old_price}}</p>
            <p class="card-text">{{p.price}}</p>
            <p>By<a href="">{{p.vendor.title}}</a></p>
            <a href="#" class="btn btn-primary">Add to Cart</a>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

templates/core/vendor-list.html
{% comment %} {% extends "partials/base.html" %} {% endcomment %}

{% comment %} {% block context %}


{% for v in  vendors %}




{% endfor %}

{% endblock context %}
 {% endcomment %}

{% load static %}
 <!DOCTYPE html>
<html>
	
<!-- molla/index.html  22 Nov 2019 09:54:33 GMT -->
<head>
		<script type="text/javascript">
			if (top !== window) {
				top.location.href = window.location.href;
			}
			if (window.location.hash) {
				window.location.href = window.location.href.replace(window.location.hash, '');
			}
		</script>

		<!-- Basic -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">

		<title>Molla - Best Premium HTML Template</title>

		<meta name="author" content="p-Themes">

		<!-- Favicon -->
		<link rel="shortcut icon" href="https://www.portotheme.com/html/molla/assets/images/demos-img/favicon.ico" type="image/x-icon" />
		<link rel="apple-touch-icon" href="../../../www.portotheme.com/html/molla/assets/images/demos-img/apple-touch-icon.html">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">

		<!-- Web Fonts  -->
		<link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700,800" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="{% static 'lib/bootstrap/bootstrap.min.css' %}">

		<!-- Theme CSS -->
		<link rel="stylesheet" href="{% static 'assets/css/main.min.css' %}">

         <!-- Plugins CSS File -->
    <!-- <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/owl-carousel/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/magnific-popup/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/plugins/jquery.countdown.css' %}"> -->
    <!-- Main CSS File -->
    <!-- <link rel="stylesheet" href="{% static 'assets/css/style.css' %}"> -->
    <link rel="stylesheet" href="{% static 'assets/css/skins/skin-demo-13.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/demos/demo-13.css' %}">

	</head>
	<body>
		<div class="page-wrapper">
			<header id="header">
				<div class="container-lg">
					<div class="header-left">
						<div class="logo">
							{% comment %} <a href="#"><img src="{% static 'assets/images/demos-img/logo.png' %}" alt="Molla Logo"></a> {% endcomment %}
                            <img src="{% static 'assets/images/demos/demo-13/logo.png' %}" alt="Manuel Logo" width="105" height="25">

						</div>
					</div>
					<div class="header-main">
						<ul class="menu">
							<li>
								<a href="#" class="goto-demos">Demos</a>
							</li>
							<li>
								<a href="#" class="goto-features">Features</a>
							</li>
							<li>
								<a href="#" class="goto-elements">Elements</a>
							</li>
							<li>
								<a href="#" class="goto-support">Support</a>
							</li>
						</ul>
					</div>
					<div class="header-right">
						<a class="mobile-menu-toggler mr-0 mr-sm-5"><i class="icon-bars"></i></a>
						<a class="btn btn-outline-primary-2 btn-outline" ><i class="icon-shopping-cart"></i>Buy Molla</a>
					</div>
				</div>
			</header>
			<div id="main">
				<section class="banner section-dark" style="background: #222;">
					<img src="{% static 'assets/images/demos-img/header_splash.jpg' %}" alt="" width="1920" height="1120">
					<div class="banner-text text-center">
						<h1>Molla eCommerce </h1>
						<h5 class="mb-5">Molla is simply the best choice for your new website. Your search for the best solution is over, get your own copy and join thousands of happy customers.</h5>
						<p class="mb-0"><a href="#" class="btn btn-outline-primary-2 btn-outline goto-demos">Explore Vendors<i class="icon-long-arrow-alt-down"></i></a></p>
					</div>
				</section>
				<section class="section section-demos text-center container-lg">
					{% comment %} <h2>20 Pre-Build Demos</h2> {% endcomment %}
					{% comment %} <p>Comes with 20 homepages available with multi style that better for your choice.<br>Molla store is one of the best Multi-Purpose eCommerce HTML Template for your store.</p> {% endcomment %}
					<div class="demo-filter menu">
						<a href="#" class="active">Vendors</a>
						
					</div>






                    <div>
                        <p>Number of vendors: {{vendors.count}}</p>
                    </div>

					<div class="row demos">
						
                        {% for v in vendors %}

						<div class="iso-item col-sm-6 col-md-4 col-lg-3 homepages">
							<a href="{% url 'core:vendor_detail_view' v.vid %}" target="_blank">
								<img src="{{v.image.url}}" data-oi="{{v.image.url}}" width="200" height="100" class="molla-lz" style="padding-top: 77%" alt=" {{v.title}}'s images">
								<h5> {{v.title}}</h5>  
                                <p>{{v.contact}}</p>
                                <p>{{v.address}}</p>
                                <div>
                                    <span>{{v.products.all.count}} Products</span>
                                    <p>{{v.date}}</p>
                                </div>
							</a>
						</div>

                        {% endfor %}
                            
                      
							





					
					{% comment %} <h5 class="text-load-more">More New Demos Coming Soon ...</h5> {% endcomment %}
				</section>

				<section class="section section-features">
					<h2 class="text-center">Our Core Features</h2>
					<p class="text-center">Powerful features and inclusions, which makes Molla standout,<br>easily customizable and scalable.</p>
					<div class="divider-line">
						<div class="container-lg">
							<div class="overflow-hidden">
								<div class="row">
									<div class="col-sm-6 col-lg-3">
										<div class="icon-box">
											<i class="icon-laptop"></i>
											<h4>Fully Responsive Design Layouts</h4>
											<p>The Template looks good and sharp with all kind of devices and screen sizes. which increase the layout flexibility.</p>
										</div>
									</div>
									<div class="col-sm-6 col-lg-3">
										<div class="icon-box">
											<i class="icon-code"></i>
											<h4>Clean And Professional Codes</h4>
											<p>The Template is ready with clean and well structured coding style by the Professional developers team.</p>
										</div>
									</div>
									<div class="col-sm-6 col-lg-3">
										<div class="icon-box">
											<i class="icon-fill-drip"></i>
											<h4>Creative And Modern Design Layout</h4>
											<p>Every single section is created with the passion and years of experience in the website development.</p>
										</div>
									</div>
									<div class="col-sm-6 col-lg-3">
										<div class="icon-box">
											<i class="icon-align-left"></i>
											<h4>Perfect Documentations</h4>
											<p>There are lots of creative section for you. So we have create a documentation that will helpful to understand the flow.</p>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="container-lg">
							<div class="overflow-hidden">
								<div class="row">
									<div class="col-sm-6 col-lg-3">
										<div class="icon-box">
											<i class="icon-th"></i>
											<h4>Build With Bootstrap</h4>
											<p>This Template is created with latest bootstrap version which used its new classes and tags.</p>
										</div>
									</div>
									<div class="col-sm-6 col-lg-3">
										<div class="icon-box">
											<i class="icon-envelope-open-text"></i>
											<h4>Working Contact Form</h4>
											<p>There are different different styled form layouts that used to get in touch with you.</p>
										</div>
									</div>
									<div class="col-sm-6 col-lg-3">
										<div class="icon-box">
											<i class="icon-cogs"></i>
											<h4>Easily Customizable</h4>
											<p>The design is fully customizable. Unlimited color styles, all 500+ Google fonts, and etc!</p>
										</div>
									</div>
									<div class="col-sm-6 col-lg-3">
										<div class="icon-box">
											<i class="icon-html5" style="font-size: 2.4rem;""></i>
											<h4>Valid HTML 5 And CSS 3</h4>
											<p>We have used latest HTML and Css Coding style that makes the pages in well working state.</p>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</section>

				
				<section class="section section-support section-dark">
					<div class="container molla-lz text-center" data-oi="assets/images/demos-img/support_bg.jpg">
						<h2>Outstaning Support Center<span class="fw-400">+</span>Extensive Documentation</h2>
						<p>Support is one of our priorities, our dedicatated support<br>will be waiting for you if you have any questions.</p>
					</div>
				</section>
				<section class="section section-light section-ready container text-center">
					<h2 class="mb-3">Molla Is Ready To Use. Get It Now!</h2>
					<p>DON'T FORGET TO APPRECIATE OUR WORK. RATE US NOW!</p>
					<div class="star-rating mb-4 pb-3">
						<i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i>
					</div>
					<p><a class="btn btn-primary btn-outline" href="#"><i class="icon-shopping-cart"></i>Buy Molla</a></p>
				</section>
			</div>
			<footer id="footer" class="container-lg">
				<div class="row">
					<div class="col-md-6 text-center text-md-left mb-4 mb-md-0">
						<p class="copyright mb-0"><a href="templateshub.net">Templateshub</a></p>
					</div>
					<div class="col-md-6 text-center text-md-right social-icons">
						<label class="mr-3">Social Media</label>
						<a href="#" title="Facebook"><i class="icon-facebook-f"></i></a>
						<a href="#" title="Twitter"><i class="icon-twitter"></i></a>
						<a href="#" title="Instagram"><i class="icon-instagram"></i></a>
						<a href="#" title="Youtube"><i class="icon-youtube"></i></a>
						<a href="#" title="Pinterest"><i class="icon-pinterest"></i></a>
					</div>
				</div>
			</footer>
		</div>

		<!-- Mobile Menu -->
		<div class="mobile-menu-overlay"></div><!-- End .mobil-menu-overlay -->

		<div class="mobile-menu-container">
			<div class="mobile-menu-wrapper">
				<span class="mobile-menu-close"><i class="icon-close"></i></span>

				<nav class="mobile-nav">
					<ul class="mobile-menu">
						<li>
							<a href="#" class="goto-demos">Demos</a>
						</li>
						<li>
							<a href="#">Features</a>
						</li>
						<li>
							<a href="#">Elements</a>
						</li>
						<li>
							<a href="#">Support</a>
						</li>
					</ul>
				</nav><!-- End .mobile-nav -->

				<div class="d-flex justify-content-center social-icons">
					<a href="#" class="social-icon" target="_blank" title="Facebook"><i class="icon-facebook-f"></i></a>
					<a href="#" class="social-icon" target="_blank" title="Twitter"><i class="icon-twitter"></i></a>
					<a href="#" class="social-icon" target="_blank" title="Instagram"><i class="icon-instagram"></i></a>
					<a href="#" class="social-icon" target="_blank" title="Youtube"><i class="icon-youtube"></i></a>
				</div><!-- End .social-icons -->
			</div><!-- End .mobile-menu-wrapper -->
		</div><!-- End .mobile-menu-container -->

		<!-- Vendor -->
		<script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
		<script src="{% static 'lib/jquery.appear/jquery.appear.min.js' %}"></script>
		<!--<script src="{% static 'lib/popper/umd/popper.min.js' %}"></script>-->
		<script src="{% static 'lib/jquery.lazyload/jquery.lazyload.min.js' %}"></script>
		<script src="{% static 'lib/isotope/jquery.isotope.min.js' %}"></script>
		
		<!-- Theme Base, Components and Settings -->
		<script src="{% static 'assets/main.js' %}"></script>
	</body>

<!-- molla/index.html  22 Nov 2019 09:54:50 GMT -->
</html>

templates/core/vendor_detail_view.html
<div>
    <img src="{{vendor.cover_image.url}}" alt="">
    <img src="{{vendor.image.url}}" alt="">
</div>

<div><span>{{vendor.date|date:"Y"}}</span></div>