core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    # home
    path('', views.index, name='index13'),
    path("product/", views.product_list_view, name='product-list'),

    # catygory
    path("category/", views.category_list, name='category-list'),
    path("category/<cid>", views.category_product_list, name='category_product_list'),
    
    # vendor
    path("vendor/", views.vendor_list_view, name='vendor_list'),
    path("vendor/<vid>", views.vendor_detail_view, name='vendor_detail_view'),

]

ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('user/',include('userauths.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from . import views

app_name = 'userauths'
urlpatterns = [
    path('register/',views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
   

]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    # about = models.CharField(max_length=100, null=True)
    bio = models.CharField(max_length=100, null=True)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']


    def __str__(self):
        return self.username

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User


class UserRegisterForm(UserCreationForm ):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':"Username"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':"Email"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':"Password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':"Confirm Password"}))

    class Meta:
        model =User
        fields = ['username', 'email']

userauths/views.py
from django.shortcuts import render, redirect
from userauths.forms import UserRegisterForm
from django.contrib.auth import login, authenticate,logout
from django.contrib import messages
from django.conf import settings
from userauths.models import User

# User = settings.AUTH_USER_MODEL



def register_view(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Hey {username}, your account was created successfully.")
            
            # Authenticate and login the user
            new_user = authenticate(username=form.cleaned_data['email'], 
                                    password=form.cleaned_data['password1'])
            if new_user is not None:
                login(request, new_user)
                return redirect('core:index13')
            else:
                messages.error(request, "Authentication failed. Please try again.")
    else:
        form = UserRegisterForm()

    context = {
        'form': form,   
    }

    return render(request, 'userauths/register.html', context)


def login_view (request):
    if request.user.is_authenticated:
        messages.warning(request, "You are already loged in.")
        return redirect('core:index13')
    
    if request.method == 'POST':
        email =request.POST.get('email')
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, 'you are logged in.')
                return redirect('core:index13')
            else:
                messages.warning(request, "User does not Exist, Create an account.")

        except:
            messages.warning(request, f'User with {email} does not exist')


    return render(request,"userauths/login.html")

def logout_view(request):
    logout(request)
    messages.warning(request, "You are loged Out.")
    return redirect ('userauths:login')

templates/userauths/login_test.html
            <form action="" method="POST">
                {% csrf_token %}
                <!-- <label for="email">Email </label> -->
                <input type="text" id="email" name="email" placeholder="email" required>
                <!--  -->
                <!-- <label for="password">Password</label> -->
                <input type="password" id="password" name="password" placeholder="password" required>
                

                <button type="submit" class="btn-continue">Continue</button>
            </form>
            <p>By continuing, you agree to GOline's <a href="#">Conditions of Use</a> and <a href="#">Privacy Notice</a>.</p>
            <div class="help-section">
                <a href="#">Need help?</a>
                <p>Buying for work? <a href="#">Shop on GOline Business</a></p>
            </div>
            <div class="new-user">
                <p>New to Amazon? <a href="{% url 'userauths:register' %}">Create your GOline account</a></p>
            <

templates/userauths/register_test.html
{% extends "core/base.html" %}


{% block content %}


{% if form.errors %}
            <div style="background-color: red;">
                {{ form.errors }}
            
            </div>
            {% endif %}
            
            
            <form action="" method="POST">
                {% csrf_token %}
                <!-- {% csrf_token %} -->
    
                <p> {{form.username}} </p>
               <p>{{form.email}} </p>
               
               <p>{{form.password1}} </p>
               <p>{{form.password2}}</p> 
               

                <button type="submit" class="btn-continue">Continue</button>
            </form>
           
            <div class="new-user">
                <p>I already have an account <a href="{% url 'userauths:login' %}">Login your GOline account</a></p>
            </div>
            {% endblock %}

templates/userauths/sign-up.html
{% extends "core/base.html" %}

{% load static %}
{% block content %}

<!-- <h1>SIGN UP PAGES</h1> -->

   <link rel="shortcut icon" href="{% static 'assets/img/theme/logo.jpeg' %}" type="image/x-icon">
    <style>
        body {
    font-family: Arial, sans-serif;
    background-color: #f7f7f7;
    margin: 0;
    padding: 0;
}

.container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
}

.form-box {
    background-color: white;
    padding: 40px;
    border-radius: 8px;
    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
    width: 350px;
    text-align: center;
}

.logo {
    width: 150px;
    margin-bottom: 20px;
}

h2 {
    font-size: 24px;
    margin-bottom: 20px;
}

label {
    display: block;
    margin-bottom: 8px;
    font-size: 14px;
    color: #333;
}

input {
    width: 100%;
    padding: 12px;
    margin-bottom: 20px;
    border: 1px solid #ccc;
    border-radius: 4px;
}

.btn-continue {
    background-color: #f0a500;
    color: white;
    padding: 12px 0;
    width: 100%;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

.btn-continue:hover {
    background-color: #e38900;
}

p {
    font-size: 12px;
    color: #555;
}

a {
    color: #0066c0;
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}

.help-section {
    margin-top: 20px;
}

.new-user {
    margin-top: 20px;
}

    </style>

</head>
<body>
    <div class="container">
        <div class="form-box">
            <img src="{% static 'assets/img/theme/logo.jpeg' %}" style="width: 20%;" alt="Amazon" class="logo">
            <!-- <h2>Sign in</h2> -->
            {% if form.errors %}
            <div style="background-color: red;">
                {{ form.errors }}
            
            </div>
            {% endif %}
            
            
            <form action="" method="POST">
                {% csrf_token %}
                <!-- {% csrf_token %} -->
    
                <p> {{form.username}} </p>
               <p>{{form.email}} </p>
               
               <p>{{form.password1}} </p>
               <p>{{form.password2}}</p> 
                <!-- <label for="email">Email </label>
                 <input type="text" id="username" name="Username" placeholder="Username" required>
                <input type="text" id="email" name="email" placeholder="email" required>
                 -->
                <!-- <label for="password">Password</label>
                <input type="password" id="password" name="password" placeholder="password" required>
                <input type="password" id="password" name="password" placeholder="password" required>
                 --> 

                <button type="submit" class="btn-continue">Continue</button>
            </form>
           
            <div class="new-user">
                <p>I already have an account <a href="{% url 'userauths:login' %}">Login your GOline account</a></p>
            </div>
        </div>
    </div>
</body>
</html>



{% endblock %}

templates/userauths/test.html
 <!-- Sign in / Register Modal -->
 <div class="modal fade" id="signin-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="icon-close"></i></span>
                </button>

                <div class="form-box">
                    <div class="form-tab">
                        <ul class="nav nav-pills nav-fill nav-border-anim" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="signin-tab" data-toggle="tab" href="#signin" role="tab" aria-controls="signin" aria-selected="true">Sign In</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="register-tab" data-toggle="tab" href="#register" role="tab" aria-controls="register" aria-selected="false">Register</a>
                            </li>
                        </ul>
                        <div class="tab-content" id="tab-content-5">
                            <div class="tab-pane fade show active" id="signin" role="tabpanel" aria-labelledby="signin-tab">
                                <form action="#">
                                    <div class="form-group">
                                        <label for="singin-email">Username or email address *</label>
                                        <input type="text" class="form-control" id="singin-email" name="singin-email" required>
                                    </div><!-- End .form-group -->

                                    <div class="form-group">
                                        <label for="singin-password">Password *</label>
                                        <input type="password" class="form-control" id="singin-password" name="singin-password" required>
                                    </div><!-- End .form-group -->

                                    <div class="form-footer">
                                        <button type="submit" class="btn btn-outline-primary-2">
                                            <span>LOG IN</span>
                                            <i class="icon-long-arrow-right"></i>
                                        </button>

                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="signin-remember">
                                            <label class="custom-control-label" for="signin-remember">Remember Me</label>
                                        </div><!-- End .custom-checkbox -->

                                        <a href="#" class="forgot-link">Forgot Your Password?</a>
                                    </div><!-- End .form-footer -->
                                </form>
                                <div class="form-choice">
                                    <p class="text-center">or sign in with</p>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <a href="#" class="btn btn-login btn-g">
                                                <i class="icon-google"></i>
                                                Login With Google
                                            </a>
                                        </div><!-- End .col-6 -->
                                        <div class="col-sm-6">
                                            <a href="#" class="btn btn-login btn-f">
                                                <i class="icon-facebook-f"></i>
                                                Login With Facebook
                                            </a>
                                        </div><!-- End .col-6 -->
                                    </div><!-- End .row -->
                                </div><!-- End .form-choice -->
                            </div><!-- .End .tab-pane -->
                            <div class="tab-pane fade" id="register" role="tabpanel" aria-labelledby="register-tab">
                                <form action="#">
                                    <div class="form-group">
                                        <label for="register-email">Your email address *</label>
                                        <input type="email" class="form-control" id="register-email" name="register-email" required>
                                    </div><!-- End .form-group -->

                                    <div class="form-group">
                                        <label for="register-password">Password *</label>
                                        <input type="password" class="form-control" id="register-password" name="register-password" required>
                                    </div><!-- End .form-group -->

                                    <div class="form-footer">
                                        <button type="submit" class="btn btn-outline-primary-2">
                                            <span>SIGN UP</span>
                                            <i class="icon-long-arrow-right"></i>
                                        </button>

                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="register-policy" required>
                                            <label class="custom-control-label" for="register-policy">I agree to the <a href="#">privacy policy</a> *</label>
                                        </div><!-- End .custom-checkbox -->
                                    </div><!-- End .form-footer -->
                                </form>
                                <div class="form-choice">
                                    <p class="text-center">or sign in with</p>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <a href="#" class="btn btn-login btn-g">
                                                <i class="icon-google"></i>
                                                Login With Google
                                            </a>
                                        </div><!-- End .col-6 -->
                                        <div class="col-sm-6">
                                            <a href="#" class="btn btn-login  btn-f">
                                                <i class="icon-facebook-f"></i>
                                                Login With Facebook
                                            </a>
                                        </div><!-- End .col-6 -->
                                    </div><!-- End .row -->
                                </div><!-- End .form-choice -->
                            </div><!-- .End .tab-pane -->
                        </div><!-- End .tab-content -->
                    </div><!-- End .form-tab -->
                </div><!-- End .form-box -->
            </div><!-- End .modal-body -->
        </div><!-- End .modal-content -->
    </div><!-- End .modal-dialog -->
</div><!-- End .modal -->